import {
	IHookFunctions,
	IWebhookFunctions,
	INodeType,
	INodeTypeDescription,
	IWebhookResponseData,
	NodeConnectionType,
} from 'n8n-workflow';
import { randomUUID } from 'crypto';
import { validateWebhookAuth } from '../utils/webhookAuth';

export class EnreachTrigger implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Enreach Trigger',
		name: 'enreachTrigger',
		icon: 'file:enreach.svg',
		group: ['trigger'],
		version: 2,
		subtitle: '={{$parameter["webhookPath"]}}',
		description: 'Listen for Enreach webhook events (SMS delivery, failures, etc.)',
		defaults: {
			name: 'Enreach Trigger',
		},
		inputs: [],
		outputs: [NodeConnectionType.Main],
		credentials: [
			{
				name: 'enreachApi',
				required: true,
			},
		],
		webhooks: [
			{
				name: 'default',
				httpMethod: 'POST',
				responseMode: 'onReceived',
				path: '={{$parameter["webhookPath"]}}',
				isFullPath: true,
			},
		],
		properties: [
			{
				displayName: 'Webhook Path',
				name: 'webhookPath',
				type: 'string',
				default: randomUUID(),
				placeholder: 'webhook',
				description: 'The custom path for the webhook URL (UUID generated by default, can be customized)',
				required: true,
			},
			{
				displayName: 'Pic',
				name: 'events',
				type: 'multiOptions',
				noDataExpression: true,
				options: [
					{
						name: 'Chat history in conversation',
						value: 'chat.history.conversation',
						description: 'Triggered for chat history events in conversation',
					},
					{
						name: 'ACD call qualification',
						value: 'acd.call.qualification',
						description: 'Triggered for ACD call qualification events',
					},
				],
				default: ['chat.history.conversation'],
				description: 'Select which events should trigger this webhook',
				required: true,
			},
		],
	};

	webhookMethods = {
		default: {
			async checkExists(this: IHookFunctions): Promise<boolean> {
				const webhookData = this.getWorkflowStaticData('node');
				
				if (webhookData.webhookId === undefined) {
					return false;
				}

				return true;
			},

			async create(this: IHookFunctions): Promise<boolean> {
				const webhookUrl = this.getNodeWebhookUrl('default');
				const events = this.getNodeParameter('events') as string[];

				const response = {
					id: `webhook_${Date.now()}`,
					url: webhookUrl,
					events: events,
				};

				const webhookData = this.getWorkflowStaticData('node');
				webhookData.webhookId = response.id;
				webhookData.webhookUrl = webhookUrl;
				webhookData.events = events;

				return true;
			},

			async delete(this: IHookFunctions): Promise<boolean> {
				const webhookData = this.getWorkflowStaticData('node');
				
				if (webhookData.webhookId) {
					delete webhookData.webhookId;
					delete webhookData.webhookUrl;
					delete webhookData.events;
				}

				return true;
			},
		},
	};

	async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
		// Get webhook body
		const bodyData = this.getBodyData();
		const jwt = bodyData.jwt as string;

		// Validate JWT authentication
		const authResult = await validateWebhookAuth(this, jwt);

		if (!authResult.isValid) {
			return {
				webhookResponse: {
					status: authResult.error!.status,
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({
						error: authResult.error!.error,
						message: authResult.error!.message
					}),
				},
			};
		}

		// Get selected events and format response
		const selectedEvents = this.getNodeParameter('events') as string[];

		return {
			workflowData: [[
				{
					json: {
						callbackUrl: bodyData.callbackUrl as string,
						id: bodyData.id as string,
						jwt: jwt,
						sid: bodyData.sid as string,
						picAppEvents: selectedEvents,
						...bodyData,
					},
				},
			]],
		};
	}
}
