import {
	IHookFunctions,
	IWebhookFunctions,
	INodeType,
	INodeTypeDescription,
	IWebhookResponseData,
	NodeConnectionType,
} from 'n8n-workflow';
import { randomUUID } from 'crypto';
import { JwtValidator } from '../utils/JwtValidator';

export class EnreachTrigger implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Enreach Trigger',
		name: 'enreachTrigger',
		icon: 'file:enreach.svg',
		group: ['trigger'],
		version: 2,
		subtitle: '={{$parameter["webhookPath"]}}',
		description: 'Listen for Enreach webhook events (SMS delivery, failures, etc.)',
		defaults: {
			name: 'Enreach Trigger',
		},
		inputs: [],
		outputs: [NodeConnectionType.Main],
		credentials: [
			{
				name: 'jwtAuth',
				required: true,
			},
		],
		webhooks: [
			{
				name: 'default',
				httpMethod: 'POST',
				responseMode: 'onReceived',
				path: '={{$parameter["webhookPath"]}}',
				isFullPath: true,
			},
		],
		properties: [
			{
				displayName: 'Webhook Path',
				name: 'webhookPath',
				type: 'string',
				default: randomUUID(),
				placeholder: 'webhook',
				description: 'The custom path for the webhook URL (UUID generated by default, can be customized)',
				required: true,
			},
			{
				displayName: 'Pic',
				name: 'events',
				type: 'multiOptions',
				noDataExpression: true,
				options: [
					{
						name: 'Chat history in conversation',
						value: 'chat.history.conversation',
						description: 'Triggered for chat history events in conversation',
					},
					{
						name: 'ACD call qualification',
						value: 'acd.call.qualification',
						description: 'Triggered for ACD call qualification events',
					},
				],
				default: ['chat.history.conversation'],
				description: 'Select which events should trigger this webhook',
				required: true,
			},
		],
	};

	webhookMethods = {
		default: {
			async checkExists(this: IHookFunctions): Promise<boolean> {
				const webhookData = this.getWorkflowStaticData('node');
				
				if (webhookData.webhookId === undefined) {
					return false;
				}

				return true;
			},

			async create(this: IHookFunctions): Promise<boolean> {
				const webhookUrl = this.getNodeWebhookUrl('default');
				const events = this.getNodeParameter('events') as string[];

				const response = {
					id: `webhook_${Date.now()}`,
					url: webhookUrl,
					events: events,
				};

				const webhookData = this.getWorkflowStaticData('node');
				webhookData.webhookId = response.id;
				webhookData.webhookUrl = webhookUrl;
				webhookData.events = events;

				return true;
			},

			async delete(this: IHookFunctions): Promise<boolean> {
				const webhookData = this.getWorkflowStaticData('node');
				
				if (webhookData.webhookId) {
					delete webhookData.webhookId;
					delete webhookData.webhookUrl;
					delete webhookData.events;
				}

				return true;
			},
		},
	};

	async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
		// Get webhook body first
		const bodyData = this.getBodyData();
		
		// JWT Authentication validation (always required)
		try {
				// Get JWT credentials (using n8n's native jwtAuth)
				const credentials = await this.getCredentials('jwtAuth');
				
				if (!credentials) {
					return {
						webhookResponse: {
							status: 401,
							headers: {
								'Content-Type': 'application/json',
							},
							body: JSON.stringify({ 
								error: 'Unauthorized',
								message: 'JWT credentials not configured'
							}),
						},
					};
				}
				
				// Extract secret based on key type
				const jwtSecret = JwtValidator.extractJwtSecret(credentials);
				
				// Algorithm is available in credentials.algorithm
				// const algorithm = credentials.algorithm as string;
				
				// For now, we don't validate expiry - could be added later if needed
				const validateExpiry = false;
				
				// Extract JWT from body (Enreach sends JWT in body)
				const jwt = bodyData.jwt as string;
				
				if (!jwt) {
					return {
						webhookResponse: {
							status: 401,
							headers: {
								'Content-Type': 'application/json',
							},
							body: JSON.stringify({ 
								error: 'Unauthorized',
								message: 'JWT token missing in request body'
							}),
						},
					};
				}
				
				// Validate JWT
				const isValid = JwtValidator.validateJWT(jwt, jwtSecret, validateExpiry);
				
				if (!isValid) {
					return {
						webhookResponse: {
							status: 401,
							headers: {
								'Content-Type': 'application/json',
							},
							body: JSON.stringify({ 
								error: 'Unauthorized',
								message: 'Invalid or expired JWT token'
							}),
						},
					};
				}
				
				// JWT decoded for debugging only in development
				// const decoded = JwtValidator.decodeJWT(jwt);
			} catch (error) {
			// JWT authentication error
			return {
				webhookResponse: {
					status: 401,
					headers: {
						'Content-Type': 'application/json',
					},
					body: JSON.stringify({ 
						error: 'Authentication failed',
						message: 'JWT validation error'
					}),
				},
			};
		}
		
		// Continue with normal webhook processing after successful authentication
		const selectedEvents = this.getNodeParameter('events') as string[];

		// Extract Enreach specific data from the webhook payload
		const callbackUrl = bodyData.callbackUrl as string;
		const id = bodyData.id as string;
		const jwt = bodyData.jwt as string;
		const sid = bodyData.sid as string;

		return {
			workflowData: [
				[
					{
						json: {
							// Enreach webhook data
							callbackUrl: callbackUrl,
							id: id,
							jwt: jwt,
							sid: sid,
							// Additional metadata
							picAppEvents: selectedEvents,
							// Include all original data for flexibility
							...bodyData,
						},
					},
				],
			],
		};
	}
}
